# Generated by Django 2.0.3 on 2018-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180329_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(default='', max_length=1),
        ),
    ]
