# Generated by Django 2.0.3 on 2018-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20180331_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
