# Generated by Django 2.0.3 on 2018-04-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20180331_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
