# Generated by Django 2.0.3 on 2018-04-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
